/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.MeseroController;
import Controller.PedidoController;
import Model.Mesero;
import Model.Pedido;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author EQUIPO 2020
 */
public class ReportesMeseroView extends javax.swing.JFrame {
    
    private PedidoController pc ;
    private List<Pedido> p;
    private List<Mesero> m;
    private MeseroController meseroControl;
    
    private DefaultTableModel modelPedidos = new DefaultTableModel(){
        public boolean isCellEditable(int fila, int columna){
            
            return false;
        }
    };

    /**
     * Creates new form ReportesMeseroView
     */
    public ReportesMeseroView() {
        pc = new PedidoController();
        meseroControl= new MeseroController();
        m = (ArrayList)meseroControl.listarMeseros();
       
        initComponents();
        cargarJComboMeseros();
        armarCabecera();
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jComboMesero = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jBVolver = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jrbPedidosAtendidos = new javax.swing.JRadioButton();
        jrbPedidosCobrados = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Seleccione un mesero:");

        jComboMesero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboMeseroActionPerformed(evt);
            }
        });

        jLabel2.setText("Resultados");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jBVolver.setText("Volver");
        jBVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBVolverActionPerformed(evt);
            }
        });

        jLabel3.setText("Reportes mesero");

        jrbPedidosAtendidos.setText("Pedidos atendidos ");
        jrbPedidosAtendidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbPedidosAtendidosActionPerformed(evt);
            }
        });

        jrbPedidosCobrados.setText("Pedidos cobrados en el dia");
        jrbPedidosCobrados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbPedidosCobradosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(182, 182, 182)
                        .addComponent(jBVolver))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(188, 188, 188)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(169, 169, 169)
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jrbPedidosAtendidos)
                                .addGap(89, 89, 89)
                                .addComponent(jrbPedidosCobrados))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(77, 77, 77)
                                .addComponent(jComboMesero, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(66, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jComboMesero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jrbPedidosAtendidos)
                    .addComponent(jrbPedidosCobrados))
                .addGap(31, 31, 31)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addComponent(jBVolver)
                .addGap(31, 31, 31))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboMeseroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboMeseroActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jComboMeseroActionPerformed

    private void jBVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBVolverActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        AdministrarView av = new AdministrarView();
        av.setVisible(true);
    }//GEN-LAST:event_jBVolverActionPerformed

    private void jrbPedidosAtendidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbPedidosAtendidosActionPerformed
        // TODO add your handling code here:
        borrarFilas();
        jrbPedidosCobrados.setSelected(false);
        pedidosAtendidosXMesero();
        //jrbPedidosCobrados.setEnabled(false);
        
    }//GEN-LAST:event_jrbPedidosAtendidosActionPerformed

    private void jrbPedidosCobradosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbPedidosCobradosActionPerformed
        // TODO add your handling code here:
        borrarFilas();
        jrbPedidosAtendidos.setSelected(false);
        pedidosCobradosXMesero();
       // jrbPedidosAtendidos.setEnabled(false);
        
    }//GEN-LAST:event_jrbPedidosCobradosActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBVolver;
    private javax.swing.JComboBox<Mesero> jComboMesero;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JRadioButton jrbPedidosAtendidos;
    private javax.swing.JRadioButton jrbPedidosCobrados;
    // End of variables declaration//GEN-END:variables

     private void armarCabecera() {
        modelPedidos.addColumn("ID Pedido");
        modelPedidos.addColumn("ID Mesa");
        modelPedidos.addColumn("Estado");
        modelPedidos.addColumn("Fecha");
        
        jTable1.setModel(modelPedidos);
    }

    private void cargarJComboMeseros(){
        MeseroController mc = new MeseroController();
        List<Mesero> meseros = mc.listarMeseros();
        for (Mesero m : meseros) {
            jComboMesero.addItem(m);
        }
    }
    
   /* private void cargarTablaPedidos(Mesero m) {
        Boolean pedido = jCheckPedidoAtendido.isSelected();
        Boolean cobrado = jCheckPedidoCobrado.isSelected();
        
        if (pedido) {
           
            for (Pedido p : pc.pedidosxMesero(m.getIdMesero())) {
            modelPedidos.addRow(new Object[]{
                p.getIdPedido(),                
                p.getMesa().getIdMesa(),
                p.getFecha()
            });
            }
        }
        if (cobrado) {
            
            for (Pedido p : pc.getPedidosCobradosXMeseroEnElDia(m.getIdMesero() )) {
            modelPedidos.addRow(new Object[]{
                p.getIdPedido(),                
                p.getMesa().getIdMesa(),
                p.getFecha()
            });
            }
        }
        
        
        
    } */
    
    
    private void borrarFilas(){
      //getRowCount devuelve el nro total de filas de la tabla, visubles o no
        int filas = jTable1.getRowCount()-1; /*le resto 1 para usar 
ese nro como el indice de la ultima fila, borramas las filas de atras para adelante*/
        
        for(int f=filas; f>=0; f--){
          modelPedidos.removeRow(f);
        }
        
        
    }
    
    
    private void pedidosAtendidosXMesero(){
    
        Mesero meseroSelec = (Mesero)jComboMesero.getSelectedItem();
        p = (ArrayList) pc.pedidosxMesero(meseroSelec.getIdMesero());
        
        for(Pedido item: p){
            
           modelPedidos.addRow(new Object[]{
                
                item.getIdPedido(),                
                item.getMesa().getIdMesa(),
                item.getFecha()
                
            
            });
           
        }
    
    }
    
    
    private void pedidosCobradosXMesero(){
    
        Mesero meseroSelec = (Mesero)jComboMesero.getSelectedItem();
        p = (ArrayList) pc.getPedidosCobradosXMeseroEnElDia(meseroSelec.getIdMesero());
        
        for(Pedido item: p){
            
           modelPedidos.addRow(new Object[]{
                
                item.getIdPedido(),                
                item.getMesa().getIdMesa(),
                item.getFecha()
                
            
            });
           
        }
    
    }
    

}
