/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.MesaController;
import Controller.MeseroController;
import Controller.PedidoController;
import Model.Mesa;
import Model.Mesero;
import Model.Pedido;
import java.time.LocalDate;
import java.time.LocalTime;
import java.time.ZoneId;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author EQUIPO 2020
 */
public class ReportesMesaView extends javax.swing.JFrame {
     private PedidoController pc ;
    private List<Pedido> p;
    private List<Mesa> m;
    private MesaController mesaControl;
    
    
    private DefaultTableModel modelPedidos = new DefaultTableModel(){
        public boolean isCellEditable(int fila, int columna){
            
            return false;
        }
    };
    /**
     * Creates new form ReportesMesaView
     */
    public ReportesMesaView() {
        
       pc = new PedidoController();
        mesaControl= new MesaController();
        m = (ArrayList)mesaControl.listarMesas();
        
        initComponents();
        this.setLocationRelativeTo(null);
        armarCabecera();
        cargarJComboMesas();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        timeSelectorDisplay1 = new examples.TimeSelectorDisplay();
        timeSelectorDisplay2 = new examples.TimeSelectorDisplay();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jComboMesa = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaPedidosMesa = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jdcFecha = new com.toedter.calendar.JDateChooser();
        jLabel6 = new javax.swing.JLabel();
        jbVolver = new javax.swing.JButton();
        jbMostrar = new javax.swing.JButton();
        Time1 = new javax.swing.JTextField();
        Time2 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(490, 600));

        jLabel1.setText("Reportes Mesa");

        jLabel2.setText("Seleccione una mesa");

        jComboMesa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboMesaActionPerformed(evt);
            }
        });

        tablaPedidosMesa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tablaPedidosMesa);

        jLabel4.setText("Seleccione fecha");

        jLabel6.setText("Ingrese hora hasta (Formato: HH:mm)");

        jbVolver.setText("Volver");
        jbVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbVolverActionPerformed(evt);
            }
        });

        jbMostrar.setText("Mostrar");
        jbMostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbMostrarActionPerformed(evt);
            }
        });

        jLabel3.setText("Ingrese hora desde (Formato: HH:mm)");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(186, 186, 186)
                        .addComponent(jbVolver))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(167, 167, 167)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel6))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jdcFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Time1, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jComboMesa, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jbMostrar)
                                        .addComponent(Time2, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(jLabel4)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jComboMesa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(Time1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(Time2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jdcFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addComponent(jbMostrar)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addComponent(jbVolver)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbVolverActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        AdministrarView av = new AdministrarView();
        av.setVisible(true);
    }//GEN-LAST:event_jbVolverActionPerformed

    private void jComboMesaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboMesaActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jComboMesaActionPerformed

    private void jbMostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbMostrarActionPerformed
        // TODO add your handling code here:
        borrarFilas();
        cargarTablaPedidoss();
       
        
    }//GEN-LAST:event_jbMostrarActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Time1;
    private javax.swing.JTextField Time2;
    private javax.swing.JComboBox<Mesa> jComboMesa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton jbMostrar;
    private javax.swing.JButton jbVolver;
    private com.toedter.calendar.JDateChooser jdcFecha;
    private javax.swing.JTable tablaPedidosMesa;
    private examples.TimeSelectorDisplay timeSelectorDisplay1;
    private examples.TimeSelectorDisplay timeSelectorDisplay2;
    // End of variables declaration//GEN-END:variables

    private void armarCabecera() {
       // modelPedidos.addColumn("ID Pedido");
        modelPedidos.addColumn("ID Mesa");
        modelPedidos.addColumn("Estado");
        modelPedidos.addColumn("Capacidad");
        modelPedidos.addColumn("Importe");
        tablaPedidosMesa.setModel(modelPedidos);
    }
    
    
    private void cargarJComboMesas(){
        MesaController mc = new MesaController();
        List<Mesa> mesas = mc.listarMesas();
        for (Mesa i : mesas) {
            jComboMesa.addItem(i);
        }
    }
    
    
    
    
    private void borrarFilas(){
      //getRowCount devuelve el nro total de filas de la tabla, visubles o no
        int filas = tablaPedidosMesa.getRowCount()-1; /*le resto 1 para usar 
ese nro como el indice de la ultima fila, borramas las filas de atras para adelante*/
        
        for(int f=filas; f>=0; f--){
          modelPedidos.removeRow(f);
        }
        
        
    }
    
    
    
    
private void cargarTablaPedidoss() {
       
        //RECUPERO FECHA
        java.util.Date date = jdcFecha.getDate();
        LocalDate fechaSelec = date.toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
        //RECUPERO HORAS
      /*  Date horaDesde = jtHoraDesde.getSelectedTime();
        Date horaHasta = jtHoraHasta.getSelectedTime();
        LocalTime hora1 = horaDesde.toInstant().atZone(ZoneId.systemDefault()).toLocalTime();
        LocalTime hora2 = horaHasta.toInstant().atZone(ZoneId.systemDefault()).toLocalTime(); 
      */  
        
      
        LocalTime hora1 =LocalTime.parse(Time1.getText());
        LocalTime hora2 = LocalTime.parse(Time2.getText());
        
        
        //RECUPERO ID MESA
        Mesa mesaSelec = (Mesa)jComboMesa.getSelectedItem();
        //LISTA PEDIDOS
        p = (ArrayList) pc.obtenerPedidosXMesaXFechaHoras(mesaSelec.getIdMesa(),fechaSelec,hora1,hora2);
        
        
        
        //RECORRO
            for (Pedido item : p){
                modelPedidos.addRow(new Object[]{
                
                item.getMesa().getIdMesa(),
                item.isEstado(),
                item.getMesa().getCapacidad(),
                item.getImporte()
                }); 
                
                
                
            }
        
        
        
    }

}
